vich_uploader:
    db_driver: orm

    mappings:
        entreprises_images:
            uri_prefix: /images/entreprises
            upload_destination: '%kernel.project_dir%/public/images/entreprises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        documents:
            uri_prefix: /documents/uploaded_files
            upload_destination: '%kernel.project_dir%/public/documents/uploaded_files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
